//@version=4
strategy(title="Local Min Max Simple Strategy",initial_capital=1000,
     currency=currency.USD, default_qty_type=strategy.percent_of_equity,
     default_qty_value=75, commission_type=strategy.commission.cash_per_order, 
     commission_value=1.0, pyramiding=1, overlay=true)

// Inputs
startMonth = input(title="Start Month", type=input.integer, defval=1)
startYear = input(title="Start Year", type=input.integer, defval=2021)

redCandle = close < open
greenCandle = close > open
localMin = falling(close[1], 2) and rising(close, 1) and greenCandle
localMax = rising(close[1], 2) and falling(close, 1) and redCandle

LongEnter = localMin
LongExit = localMax

// Buy / Sell
if (month >= startMonth and year == startYear) or year > startYear
    strategy.entry("long", long=true, when = LongEnter)
    strategy.close("long", when = LongExit)
