//@version=4
//Created by Yasin Basaran for educational purposes , you can use it freely and i appreciate if someone make a strategy out of it :)
// Trade wise and be careful.
study(title="Oracle Algo-V1.2", shorttitle="Oracle Algo-V1.2", overlay=true, max_labels_count=500)
max_bars_back(time, 1000)
////////////////////////DYNAMIC SUPPORT AND RESISTANCE////////////
my_var = input(true, title=" 💶💶💶 Dynamic Support and Resistance Settings 💶💶💶")

length = input(20, minval=1, title="Dynamic Support and Resistance Range ")
lower = lowest(length)
upper = highest(length)
upperText = tostring(upper,"###,###.####")+(change(upper)>0?" ▲ ":" ▼ ")
lowerText = tostring(lower,"###,###.####")+(change(lower)>0?" ▲ ":" ▼ ")
line.new(0, upper, 0, upper, xloc=xloc.bar_time, extend=extend.right, color=color.black, style=line.style_solid, width=1)
line.new(0, lower, 0, lower, xloc=xloc.bar_time, extend=extend.right, color=color.red, style=line.style_solid, width=1)

///////////////BOLLINGER/////
my_var2 = input(true, title=" 💶💶💶 Bollinger Band Settings 💶💶💶")

lengthBB = input(20, minval=1)
//srcBB = input(close, title="Source")
//multBB = input(2.0, minval=0.001, maxval=50, title="StdDevBB")
basisBB = sma(close, lengthBB)
devBB = stdev(close, lengthBB) *2
upperBB = basisBB + devBB
lowerBB = basisBB - devBB
//offset = input(0, "Offset", type = input.integer, minval = -500, maxval = 500)
plot(basisBB, "Basis-BB", color=color.black,  linewidth=2 ,transp=50)
p1 = plot(upperBB, "Upper-BB", color=color.black,  linewidth=2, transp=50)
p2 = plot(lowerBB, "Lower-BB", color=color.black,  linewidth=2, transp=50)
fill(p1, p2, title = "Background-BB", color=color.blue, transp=90)

/////////////////EMA/////////
my_var3 = input(true, title=" 💶💶💶 EMA Settings 💶💶💶")

lenemin = input(50, minval=1, title="MA Fast")
outE1 = ema(close, lenemin)
E1X = plot(outE1, color=color.green, title="MA Fast", linewidth=4, transp=50)

lenemax = input(200, minval=1, title="MA Slow")
outE2 = ema(close, lenemax)
E2X = plot(outE2, color=color.red, title="MA Slow", linewidth=4, transp=50)
emarat = ( outE1 / outE2 ) - 1
emaratText=tostring(emarat,"%.##")+(change(emarat)>0?" ▲ ":" ▼ ")

fill(E1X, E2X, title="Background-EMA", color=color.red,transp=90 )

//////////////CCI//////////////
my_var4 = input(true, title=" 💶💶💶 Commodity Chanel Index Settings 💶💶💶")

lengthCCI = input(20, minval=1)
maCCI = sma(close, lengthCCI)
cci = (close - maCCI) / (0.015 * dev(close, lengthCCI))
cciText=tostring(cci,"#.##")+(change(cci)>0?" ▲ ":" ▼ ")

///////////////MACD///////////////////
my_var5 = input(true, title=" 💶💶💶 MACD Settings 💶💶💶")

fast_length = input(title="MACD Fast Length", type=input.integer, defval=5)
slow_length = input(title="MACD Slow Length", type=input.integer, defval=45)
//srcxxx = input(title="MACD Source", type=input.source, defval=close)
signal_length = input(title="MACD Signal Smoothing", type=input.integer, minval = 1, maxval = 50, defval = 5)
sma_source = input(title="MACD Simple MA(Oscillator)", type=input.bool, defval=false)
sma_signal = input(title="MACD Simple MA(Signal Line)", type=input.bool, defval=false)
fast_ma = sma_source ? sma(close, fast_length) : ema(close, fast_length)
slow_ma = sma_source ? sma(close, slow_length) : ema(close, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal ? sma(macd, signal_length) : ema(macd, signal_length)
hist = macd - signal
macdText=tostring(hist,"#.####")+(change(hist)>0?" ▲ ":" ▼ ")

/////////////DIRECTIONAL MOVEMENT INDEX////////////////
my_var6 = input(true, title=" 💶💶💶 ADX and DI Settings 💶💶💶")

lensig = input(14, title="ADX Smoothing", minval=1, maxval=50)
lendi = input(14, minval=1, title="DI Length")
updi = change(high)
downdi = -change(low)
plusDM = na(updi) ? na : (updi > downdi and updi > 0 ? updi : 0)
minusDM = na(downdi) ? na : (downdi > updi and downdi > 0 ? downdi : 0)
trur = rma(tr, lendi)
plus = fixnan(100 * rma(plusDM, lendi) / trur)
minus = fixnan(100 * rma(minusDM, lendi) / trur)
sum = plus + minus
plusText=tostring(plus,"#.####")+(change(plus)>0?" ▲ ":" ▼ ")
minusText=tostring(minus,"#.####")+(change(minus)>0?" ▲ ":" ▼ ")

///////STOCH RSI///////////
my_var7 = input(true, title=" 💶💶💶 Stoch and RSI Settings 💶💶💶")

smoothK = input(3, "K", minval=1)
smoothD = input(3, "D", minval=1)
lengthRSI = input(14, "RSI Length", minval=1)
lengthStoch = input(14, "Stochastic Length", minval=1)
srcstoch = input(close, title="RSI Source")
rsi1 = rsi(srcstoch, lengthRSI)
k = sma(stoch(rsi1, rsi1, rsi1, lengthStoch), smoothK)
d = sma(k, smoothD)
StochKText=tostring(k,"#.##")+(change(k)>0?" ▲ ":" ▼ ")
StochDText=tostring(d,"#.##")+(change(d)>0?" ▲ ":" ▼ ")
rsiText=tostring(rsi1,"#.##")+(change(rsi1)>0?" ▲ ":" ▼ ")

/////////////////WAVE TREND/////////////////
my_var8 = input(true, title=" 💶💶💶 Wave Trend Settings 💶💶💶")
n1 = input(10, "WT-Channel Length")
n2 = input(21, "Average Length")
ap = hlc3 
esa = ema(ap, n1)
dw = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * dw)
tci = ema(ci, n2)
wt1 = tci
wt2 = sma(wt1,4)
wtratText=tostring(wt1,"#.##")+(change(wt1)>0?" ▲ ":" ▼ ")

/////////////////SUPER TREND/////////////////
[supertrend, direction] = supertrend(3, 10)
upTrend = direction < 0 ? supertrend : na
downTrend = direction < 0? na : supertrend
superText = iff(upTrend >0 , "Up Trend", "Down Trend")

/////////////////BULL & BEAR INDEX/////////////////
BullPower = high - ema(close, 20)
BearPower = low - ema(close, 20)
bbindex = ((BullPower + BearPower) /2 )
bbindexText = iff(bbindex >0 , "BULL","BEAR")

/////////////// BUYING VOLUME AND SELLING VOLUME PRESSSURE////////
buyvolume = ema(iff( (high==low), 0, volume*(close-low)/(high-low)),15)
sellvolume = ema(iff( (high==low), 0, volume*(high-close)/(high-low)),15)
totalvolume = buyvolume + sellvolume
buypressure = (buyvolume / totalvolume )*100
sellpressure = (sellvolume / totalvolume)*100
buysellpressureText = iff( buypressure>sellpressure , "BUY", "SELL")


//////////////PIVOT POINTS/////////////
ph2 = pivothigh(2, 2)
pl2 = pivotlow(2, 2)
plot(ph2, title="High Pivot",style=plot.style_cross, linewidth=3, color= color.green)
plot(pl2, title="Low Pivot", style=plot.style_cross, linewidth=3, color= color.red)


//DEFINE STRATEGY
currPrice = hl2[0]
prevPrice = hl2[1]

buy = currPrice > prevPrice and emarat>0 and currPrice >outE1 and currPrice >outE2 and currPrice >basisBB and cci > 0 and macd >0 and plus > minus and k>d and wt1>wt2
sell = currPrice < prevPrice and emarat<0 and currPrice <outE1 and currPrice <outE2 and currPrice <basisBB and cci < 0 and macd <0 and plus < minus and k<d and wt1<wt2
neutral = buy == 0 and sell == 0


//////////////////DYNAMIC STOP LOSS AND TAKE PROFIT SECTION ACORDING TO SITUATION/////////
my_var9 = input(true, title=" 💶💶💶 Risk and Reward Section Settings 💶💶💶")
TP1 = input(2, "Take Profit-1 %", minval=1)
TP2 = input(4, "Take Profit-2-%", minval=1)
TP3 = input(6, "Take Profit-3-%", minval=1)

bvalx = valuewhen(currPrice > prevPrice and emarat>0 and currPrice >outE1 and currPrice >outE2 and currPrice >basisBB and cci > 0 and macd >0 and plus > minus and k>d and wt1>wt2,close,1)
plot(bvalx, color=color.green, title="Algo Upper Band", linewidth=4,transp=100)

svalx = valuewhen(currPrice < prevPrice and emarat<0 and currPrice <outE1 and currPrice <outE2 and currPrice <basisBB and cci < 0 and macd <0 and plus < minus and k<d and wt1<wt2,close,1)
plot(svalx, color=color.red, title="Algo Lower Band", linewidth=4,transp=100)

avgvalx = ( bvalx + svalx )/2
plot(avgvalx, color=color.black, title="Average Band Price", linewidth=4,transp=100)
avgvalxText=tostring(avgvalx,"###,###.####")

BTPindex = valuewhen(currPrice< avgvalx,close,1)
BTPindexText=tostring(BTPindex,"###,###.####")
STPindex = valuewhen(currPrice> avgvalx,close,1)
STPindexText=tostring(STPindex,"###,###.####")

Dynamo = ((BTPindex + STPindex)/2)

statusx= iff(currPrice>Dynamo,"BUY","SELL")
Dynamo2 = iff(statusx=="BUY",(Dynamo+BTPindex)/2, (Dynamo+STPindex)/2)
DynamoText=tostring(Dynamo2,"###,###.####")
plot(BTPindex, color=color.red, title="Buy Signal Price ", linewidth=4,transp=50)
plot(STPindex, color=color.blue, title="Sell Signal Price", linewidth=4,transp=50)
plot(Dynamo2, color=color.black, title="Dynamic Stop Loss", linewidth=4,transp=50)

btp1 = BTPindex * (1+(TP1/100))
btp1Text=iff(statusx=="BUY",tostring(btp1,"###,###.####"),"WAIT")
stp1 = STPindex * (1-(TP1/100))
stp1Text=iff(statusx=="SELL",tostring(stp1,"###,###.####"),"WAIT")

btp2 = BTPindex * (1+(TP2/100))
btp2Text=iff(statusx=="BUY",tostring(btp2,"###,###.####"),"WAIT")
stp2 = STPindex * (1-(TP2/100))
stp2Text=iff(statusx=="SELL",tostring(stp2,"###,###.####"),"WAIT")

btp3 = BTPindex * (1+(TP3/100))
btp3Text=iff(statusx=="BUY",tostring(btp3,"###,###.####"),"WAIT")
stp3 = STPindex * (1-(TP3/100))
stp3Text=iff(statusx=="SELL",tostring(stp3,"###,###.####"),"WAIT")

/////////DEFINING LABELS//////
xxx = crossover(close , Dynamo)
yyy = crossunder(close , Dynamo)
plotshape(xxx , style=shape.labeldown,location=location.abovebar, color=color.green, textcolor=color.black, text="BUY", title="Buy Label", size=size.normal)
plotshape(yyy , style=shape.labelup,location=location.belowbar, color=color.red, textcolor=color.black, text="SELL",title="Sell Label", size=size.normal)

////////////DEFINING ALERTS/////////
buystop = currPrice < basisBB or currPrice<outE1 or currPrice<outE2 or currPrice<Dynamo2
sellstop = currPrice > basisBB or currPrice>outE1 or currPrice>outE2 or currPrice>Dynamo2

alertcondition( statusx=="BUY",title='BUY', message='BUY ALERT')
alertcondition( buystop==1,title='BUY TP OR STOP', message='BUY STOP OR TAKE PROFIT ALERT')
alertcondition( statusx=="SELL", title='SELL', message='SELL ALERT')
alertcondition( sellstop==1,title='SELL TP OR STOP', message='SELL STOP OR TAKE PROFIT ALERT')

/////////////////INFORMATION TABLE/////////
var infoTable = table.new(position = position.top_right, columns = 2, rows = 14, bgcolor = color.white, border_color=color.black, frame_color=color.red , border_width = 1)

if barstate.islast
    table.cell(table_id = infoTable, column = 0, row = 0, text = "ORACLE ALGO ", text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 0, text = "V1 - 08/2021" ,text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 1, bgcolor = color.black , text_color=color.white , text = "GENERAL SENSATION" , text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 1, bgcolor = color.yellow , text_color=color.black , text = ""+statusx, text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 2, bgcolor = color.black , text_color=color.white , text = "SUPPORT" , text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 2, bgcolor = color.black , text_color=color.white , text = "RESISTANCE", text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 3, text = ""+lowerText , text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 3, text = ""+upperText, text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 4, bgcolor = color.black , text_color=color.white , text = "KPI ", text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 4, bgcolor = color.black , text_color=color.white , text = "CONTROL", text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 5, text = "CCI :"+cciText,bgcolor=iff(cci >0 , color.green , color.red), text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 5, text = "MACD :"+macdText,bgcolor=iff(hist >0 , color.green , color.red) ,text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 6, text = "DI+ :"+ plusText,bgcolor=iff(plus >minus , color.green , color.red) , text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 6, text = "DI- :"+ minusText, bgcolor=iff(plus >minus , color.green , color.red) ,text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 7, text = "ST-K :"+StochKText,bgcolor=iff(k>d , color.green , color.red), text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 7, text = "ST-D :"+StochDText,bgcolor=iff(k>d , color.green , color.red), text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 8, bgcolor = color.black , text_color=color.white , text = "TREND ", text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 8, bgcolor = color.black , text_color=color.white , text = "CONTROL", text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 9, text = "EMA 50/250 % :"+ emaratText, bgcolor=iff(emarat >0 , color.green , color.red) ,text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 9, text = "RSI :"+rsiText, text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 10, text = "WT :"+ wtratText,bgcolor=iff(wt1>wt2 , color.green , color.red), text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 10, text = "ST :" + superText, text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 11, bgcolor = color.black , text_color=color.white , text = "POWER ", text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 11, bgcolor = color.black , text_color=color.white , text = "CONTROL", text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 12, text = "BULL/BEAR INDEX " , text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 12, text = "VOLUME PRESSURE ", text_size=size.small)

    table.cell(table_id = infoTable, column = 0, row = 13, text = "" + bbindexText, bgcolor= iff(bbindex >0 , color.green , color.red) ,text_size=size.small)
    table.cell(table_id = infoTable, column = 1, row = 13, text = "" + buysellpressureText, bgcolor= iff( buypressure>sellpressure , color.green , color.red) ,text_size=size.small)

/////////////////ORACLE ALGO - V1 /////////
var OracleTable = table.new(position = position.bottom_right, columns = 3, rows = 8, bgcolor = color.white, border_color=color.black, frame_color=color.red , border_width = 1)

if barstate.islast
    table.cell(table_id = OracleTable, column = 0, row = 0, text = "ORACLE ALGO ", text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 0, text = "RISK AND PROFIT" ,text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 0, text = "MANAGEMENT" ,text_size=size.small)

    table.cell(table_id = OracleTable, column = 0, row = 1, bgcolor = color.black , text_color=color.white , text = "GENERAL SENSATION" , text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 1, bgcolor = color.yellow , text_color=color.black , text = ""+iff(statusx=="SELL","WAIT",statusx), text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 1, bgcolor = color.yellow , text_color=color.black , text = ""+iff(statusx=="BUY","WAIT",statusx), text_size=size.small)

    table.cell(table_id = OracleTable, column = 0, row = 2, bgcolor = color.black , text_color=color.white , text = "DESCRIPTION" , text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 2, bgcolor = color.black , text_color=color.white , text = "BUY SECTION", text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 2, bgcolor = color.black , text_color=color.white , text = "SELL SECTION", text_size=size.small)

    table.cell(table_id = OracleTable, column = 0, row = 3, bgcolor = color.black , text_color=color.white , text = "SIGNAL PRICE" , text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 3, bgcolor = color.yellow , text_color=color.black , text = ""+iff(statusx=="SELL" or statusx=="WAIT" ,"WAIT",BTPindexText), text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 3, bgcolor = color.yellow , text_color=color.black , text = ""+iff(statusx=="BUY" or statusx=="WAIT","WAIT",STPindexText), text_size=size.small)

    table.cell(table_id = OracleTable, column = 0, row = 4, bgcolor = color.black , text_color=color.white , text = "DYNAMIC-STOP LOSS" , text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 4, bgcolor = color.yellow , text_color=color.black , text = ""+iff(statusx=="SELL","WAIT",DynamoText), text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 4, bgcolor = color.yellow , text_color=color.black , text = ""+iff(statusx=="BUY","WAIT",DynamoText), text_size=size.small)

    table.cell(table_id = OracleTable, column = 0, row = 5, bgcolor = color.black , text_color=color.white , text = "TAKE PROFIT#1" , text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 5, bgcolor = iff(hl2 > btp1 , color.green , color.yellow) , text_color=color.black , text = ""+btp1Text, text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 5, bgcolor = iff(hl2 < stp1 , color.green , color.yellow) , text_color=color.black , text = ""+stp1Text, text_size=size.small)

    table.cell(table_id = OracleTable, column = 0, row = 6, bgcolor = color.black , text_color=color.white , text = "TAKE PROFIT#2" , text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 6, bgcolor = iff(hl2 > btp2 , color.green , color.yellow), text_color=color.black , text = ""+btp2Text, text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 6, bgcolor = iff(hl2 < stp2 , color.green , color.yellow) , text_color=color.black , text = ""+stp2Text, text_size=size.small)

    table.cell(table_id = OracleTable, column = 0, row = 7, bgcolor = color.black , text_color=color.white , text = "TAKE PROFIT#3" , text_size=size.small)
    table.cell(table_id = OracleTable, column = 1, row = 7, bgcolor = iff(hl2 > btp3 , color.green , color.yellow) , text_color=color.black , text = ""+btp3Text, text_size=size.small)
    table.cell(table_id = OracleTable, column = 2, row = 7, bgcolor = iff(hl2 < stp3 , color.green , color.yellow) , text_color=color.black , text = ""+stp3Text, text_size=size.small)
////SESSIONS////
my_var10 = input(true, title=" 💶💶💶 NY,Asia and London Market Working Hours Settings 💶💶💶")

timeinrange(res, sess) =>
    time(res, sess) != 0

//Change true to false = You have to turn on, won't show up by default
//****Always use lowercase letters

Open = input(defval=true, type=input.bool, title="Open On")
Session = input(defval=true, type=input.bool, title="Session On")
Close = input(defval=true, type=input.bool, title="Close On")


//doNYOpen = input(defval=true, type=input.bool, title="NY Open On")
//doNYSession = input(defval=true, type=input.bool, title="NY Session On")
//doNYClose = input(defval=true, type=input.bool, title="NY Close On")

//doAsiaOpen = input(defval=true, type=input.bool, title="Asia Open On")
//doAsiaSession = input(defval=true, type=input.bool, title="Asia Session On")
//doAsiaClose = input(defval=true, type=input.bool, title="Asia Close On")

//doEurOpen = input(defval=true, type=input.bool, title="Euro Open On")
//doEurSession = input(defval=true, type=input.bool, title="Euro Session On")
//doEurClose = input(defval=true, type=input.bool, title="Euro Close On")

//You can copy and paste these colors. white - silver - gray - maroon - red - purple - fuchsia - green - lime
//   olive - yellow - navy - blue - teal - aqua - orange 

nySessionStart = color.white
nySession = color.white
nySessionEnd = color.white
asiaSessionStart = #DAA520
asiaSession = #DAA520
asiaSessionEnd = #DAA520
europeSessionStart = #1E90FF
europeSession = #1E90FF
europeSessionEnd = #1E90FF

//****Note ---- Use Military Times --- So 3:00PM = 1500

bgcolor(Open and timeinrange(timeframe.period, "0800-0810") ? nySessionStart : na, transp=20)
bgcolor(Session and timeinrange(timeframe.period, "0800-1700") ? nySession : na, transp=75)
bgcolor(Close and timeinrange(timeframe.period, "1650-1700") ? nySessionEnd : na, transp=20)

bgcolor(Open and timeinrange(timeframe.period, "1900-1910") ? asiaSessionStart : na, transp=20)
bgcolor(Session and timeinrange(timeframe.period, "1900-0400") ? asiaSession : na, transp=75)
bgcolor(Close and timeinrange(timeframe.period, "0350-0400") ? asiaSessionEnd : na, transp=20)

bgcolor(Open and timeinrange(timeframe.period, "0300-0310") ? europeSessionStart : na, transp=20)
bgcolor(Session and timeinrange(timeframe.period, "0300-1200") ? europeSession : na, transp=75)
bgcolor(Close and timeinrange(timeframe.period, "1150-1200") ? europeSessionEnd : na, transp=20)